apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: my-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: aleena8/nextjs:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_STRAPI_API_URL
              value: "http://209.38.121.93:30002"

            - name: NEXT_PUBLIC_STRAPI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: STRAPI_API_TOKEN

            - name: NEXT_PUBLIC_STRAPI_FORM_SUBMISSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: STRAPI_FORM_SUBMISSION_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs
  namespace: my-blog
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: nextjs

