apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: my-blog
type: Opaque
data:
  POSTGRES_USER: c3RyYXBp
  POSTGRES_PASSWORD: c3RyYXBp
  POSTGRES_DB: c3RyYXBp
  STRAPI_API_TOKEN: NDczYzUzMzE3NDMxNGJjMDJkYjU1ZmI5MjFlZTQ3MDIwYw==
  STRAPI_FORM_SUBMISSION_TOKEN: Zm9vYmFyMTIzNDU2

