apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-api
  namespace: my-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: aleena8/strapi:latest
          ports:
            - containerPort: 1337
          env:
            # Database
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: POSTGRES_DB
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: POSTGRES_PASSWORD

            # REQUIRED STRAPI INTERNAL SECURITY KEYS
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: APP_KEYS

            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: API_TOKEN_SALT

            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: ADMIN_JWT_SECRET

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: JWT_SECRET

            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: TRANSFER_TOKEN_SALT

            # Frontend API token (optional)
            - name: STRAPI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: STRAPI_API_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-api
  namespace: my-blog
spec:
  type: NodePort
  ports:
    - port: 1337
      targetPort: 1337
      nodePort: 30002
  selector:
    app: strapi

