apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: my-blog
type: Opaque
stringData:
  POSTGRES_USER: strapi
  POSTGRES_PASSWORD: strapi
  POSTGRES_DB: strapi

  APP_KEYS: "key1,key2,key3"
  API_TOKEN_SALT: "salt123"
  ADMIN_JWT_SECRET: "adminjwt"
  JWT_SECRET: "jwtsecret"
  TRANSFER_TOKEN_SALT: "transfersalt"

  STRAPI_API_TOKEN: "56f6311d6d5917ae3f37e117c8a84af8d2d9ad005c559c07f26f3c748e3b454b232d614e15d562ef0c847a8b8c2abd7f4b496b8224cb64a953fb22fde751a3a6452493a9b8fa6fad320d2f0d607c1a95b39cb4b817c056617da6f667c9c6991bd060431882b9b45962d8f168db2e7b0c1f8ee48659a3e6fce6c5b095c7a0e3be"
  STRAPI_FORM_SUBMISSION_TOKEN: "5c59b61a7a75b691215490fc8a7bd0c612f6dbfe4612424375efe4da579af775fab02c4b0d9f1f723b348849e8b05e90e75672908aae257c1672a1785c1dfd1651853c10c62cecdc5b9fd1aefbce730ae0ceef52c00240a18194568844b22ab328d9717bc38a3f34e7a20cdc39e283cb5dd545505d47e1fedb0d41001a907220"

  NEXT_PUBLIC_STRAPI_API_URL: "http://209.38.121.93:30002"
